feat(wowza streaming cloud):
VS-work/live-starter pull request #24
Opened 2017-12-06 11:32 UTC by DmitriyLitvinov

- updated dependencies to angulart 5 and ngx-bootstrap 2.0.0-beta.8
- changed styleExt to SCSS in angular cli
- added wowza streaming cloud;
- added my-events page;
- added my-event component
- validated fields Lounch page
- added time picker, back btn Lounch page
- updated date picker

2017-12-07 09:34 UTC, Ugmaxie requested changes

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +    <div class="first-step" *ngIf="activeStep === 1">
avoid direct comparison in html

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +                           [id]="location.id"
check if you can use  id="location.id" without [ ]

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +                           [value]="location.name"
the same as above

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +                     [min]="50"
avoid use dual-binding [ ]

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +                     [min]="10"
min="10"

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +                     [min]="0"
min="0"

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +    <div class="second-step" *ngIf="activeStep === 2">
avoid using direct comparison in html

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
use col-9

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.html
> +        <div class="side-bar col-lg-3 col-md-3 col-sm-3 col-xs-3">
use col-3

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
>        .subscribe((res: any): void => {
avoid **any**

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
>          const styles: any = res.data;
avoid **any**

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
>        .subscribe((res: any): void => {
avoid **any**

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
> +    } else {
avoid **else**

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
> +    if (!eventForm.invalid && this.launchEvent.genres.length) {
use negative scenario at first

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
> +      .subscribe((liveStream: any) => {
use **liveStream => **

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
> +          .subscribe((res: any) => {
use **res =>**

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
> +          }, (err: any) => {
use err=>

2017-12-07 09:34 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
> +      }, (err: any) => {
the same as above

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/search-service/search.service.ts
>      return this.http.get(`${Config.api}/get-locations`).map((res: any) => {
res =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +          .subscribe((state: string) => {
state =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +            console.log('state', state);
avoid console.log

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +        console.log('showData', this.showData.wowza);
avoid console.log

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +  showData: any;
avoid any

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +      .subscribe((res: any) => {
res =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +      }, (err: any) => {
err =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +      .subscribe((res: any) => {
res =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +        console.log('stream stopped', res);
console.log

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +      }, (err: any) => {
err =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +  changeEncoder(encoder: string) {
: void

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +      .subscribe((res: any) => {
res =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +      }, (err: any) => {
err =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +      .subscribe((res: any) => {
res =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-cloud.component.ts
> +      }, (err: any) => {
err =>

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-player/wowza-player.component.ts
> +  showParams: any;
avoid any

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-player/wowza-player.component.ts
> +  player: any;
avoid any

2017-12-07 09:34 UTC, Ugmaxie commented on src/shared/wowza-streaming-cloud/wowza-player/wowza-player.component.ts
> +  parsePlayerConfig(): any {
avoid any

2017-12-07 13:30 UTC, DmitriyLitvinov commented on src/event-launch/event-launch.component.html
> +                           [id]="location.id"
I can use this  `id="{{location.id}}"` but I think  that `[id]="location.id"` more beautiful

2017-12-07 13:30 UTC, DmitriyLitvinov commented on src/event-launch/event-launch.component.html
> +                           [value]="location.name"
I can use this  `id="{{location.id}}"` but I think  that `[id]="location.id"` more beautiful

2017-12-07 14:32 UTC, DmitriyLitvinov commented on src/shared/wowza-streaming-cloud/wowza-player/wowza-player.component.ts
> +  player: any;
`player` it's an Object from Wowza Player API. Should I create interface for it?

2017-12-07 14:39 UTC, DmitriyLitvinov commented on src/shared/search-service/search.service.ts
>      return this.http.get(`${Config.api}/get-locations`).map((res: any) => {
If I remove type any I have linter Error like `_body does not exist type Response`

2017-12-08 11:26 UTC, Ugmaxie approved these changes

2017-12-08 11:27 UTC, merged