Feat page my events
VS-work/live-starter pull request #25
Opened 2017-12-11 15:43 UTC by DmitriyLitvinov

- change launchEvent inteface 
        - responcive markup for my events page
        - created show-info component
        - create statistics component
        - aded functionality for liking/unliking show

2017-12-12 10:17 UTC, valorkin requested changes

2017-12-12 10:17 UTC, valorkin commented on src/event-launch/event-launch.component.ts
>      this.launchEvent = {
Use class with default values

2017-12-12 10:17 UTC, valorkin commented on src/shared/search-service/search.service.ts
> +      .map((res: any) => {
Single resposibility
One data transformation per map call
Dont forget ti catch errors

2017-12-12 10:17 UTC, valorkin commented on src/shared/statistics/statistics.component.ts
> +  user: any;
Don't use any, provide appropriate classes

2017-12-12 10:17 UTC, valorkin commented on src/shared/statistics/statistics.component.ts
> +    this.user = JSON.parse(localStorage.getItem('profile'));
Any json.parse should be wrapped in try catch

2017-12-12 10:17 UTC, valorkin commented on src/shared/statistics/statistics.component.ts
> +    if (this.isEvent) {
Invert if

2017-12-12 10:17 UTC, valorkin commented on src/shared/statistics/statistics.service.ts
> +  private setOptions(): RequestOptions {
Its get options

2017-12-12 10:17 UTC, valorkin commented on src/shared/statistics/statistics.service.ts
> +      .map(res => {
Use one line arrow func and single responsibility

2017-12-12 10:17 UTC, valorkin commented on src/shared/statistics/statistics.service.ts
> +      }, (err: any) => {
Catch

2017-12-12 10:17 UTC, valorkin commented on src/shared/statistics/statistics.service.ts
> +      }, (err: any) => {
Review your PR and apply same to other code

2017-12-12 11:43 UTC, Ugmaxie requested changes

2017-12-12 11:43 UTC, Ugmaxie commented on src/shared/statistics/statistics.service.ts
> +        console.log('artist Like: ', res);
remove console.log

2017-12-15 12:13 UTC, Ugmaxie approved these changes

2017-12-15 12:14 UTC, Ugmaxie commented
@valorkin Your comments seems to be applied. Merging.

2017-12-15 12:15 UTC, merged