feat(user): ready for test
VS-work/live-starter pull request #32
Opened 2017-12-27 17:02 UTC by DmitriyLitvinov

2017-12-28 10:26 UTC, Ugmaxie requested changes

2017-12-28 10:26 UTC, Ugmaxie commented on src/auth/auth.service.ts
>      this.lock.on('authenticated', (authResult: any): void => {
authResult =>

2017-12-28 10:26 UTC, Ugmaxie commented on src/header/header.component.ts
>      this.localStorageService.getItemEvent().subscribe((userData: any) => {
userData =>

2017-12-28 10:26 UTC, Ugmaxie commented on src/header/header.component.ts
> +    console.log(this.userProfile);
remove

2017-12-28 10:26 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +  _id?: string;
id is optional?

2017-12-28 10:26 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +  newUser: INewUser = {
make INewUser as a class and you can use constructor: 
newUser = new NewUser();

2017-12-28 10:26 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
>        .subscribe((res): void => {
res =>

2017-12-28 10:26 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +      .subscribe((res: any) => {
res =>

2017-12-28 10:26 UTC, Ugmaxie commented on src/signup/signup.service.ts
> +  getUser(data: any): Observable<any> {
avoid any

2017-12-28 10:26 UTC, Ugmaxie commented on src/signup/signup.service.ts
> +    return (error: any): Observable<T> => {
avoid any

2017-12-28 11:45 UTC, DmitriyLitvinov commented on src/signup/second-step/second-step.component.ts
> +  _id?: string;
now it's optional

2017-12-29 10:34 UTC, Ugmaxie requested changes

2017-12-29 10:34 UTC, Ugmaxie commented on src/auth/auth.service.ts
>            alert(error);
no alerts

2017-12-29 10:34 UTC, Ugmaxie commented on src/auth/auth.service.ts
>          alert('something went wrong: ' + err.message);
no alerts

2017-12-29 10:34 UTC, Ugmaxie commented on src/header/header.component.ts
> +  userProfile: any;
no any

2017-12-29 10:34 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
>  import { extend } from 'lodash';
use lodash es and don't import whole lodash

2017-12-29 10:34 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +      .subscribe(res => {
use .filter(data => typeof data !== 'undefined')  to avoid subscription if data is undefined

2017-12-29 10:34 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +        if (res.success && res.error) {
if res.success and res.error - please clarify

2017-12-29 10:34 UTC, Ugmaxie commented on src/signup/signup.service.ts
> +  signupUser(query: any): Observable<any> {
no any

2017-12-29 10:34 UTC, Ugmaxie commented on src/signup/signup.service.ts
> +  isEmailExist(query: any): Observable<any> {
no any

2017-12-29 10:34 UTC, Ugmaxie commented on src/signup/user.class.ts
> +  constructor(user: any) {
any?

2017-12-29 11:09 UTC, DmitriyLitvinov commented on src/signup/second-step/second-step.component.ts
>  import { extend } from 'lodash';
I think we should do it in particular PR

2017-12-29 11:26 UTC, DmitriyLitvinov commented on src/signup/second-step/second-step.component.ts
> +        if (res.success && res.error) {
This is checking for an existing email and if it already exists I have a response like this `{data: null, success: true, error: 'text error'}`

2017-12-29 11:26 UTC, DmitriyLitvinov commented on src/signup/second-step/second-step.component.ts
> +      .subscribe(res => {
This is checking for an existing email and if it already exists I have a response like this `{data: null, success: true, error: 'text error'}`

2017-12-29 15:10 UTC, Ugmaxie requested changes

2017-12-29 15:10 UTC, Ugmaxie commented on src/app.config.ts
>    public static objToQuery(data: any): string {
no any

2017-12-29 15:10 UTC, Ugmaxie commented on src/app.config.ts
>    public static objToQuery(data: any): string {
no any

2017-12-29 15:36 UTC, Ugmaxie requested changes

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
>            return;
return undefined?

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +      this.lock.getProfile(authResult.idToken, (error: Error, profile: UserSocialNetworkObj) => {
what if return undefined? ;)

2017-12-29 15:36 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
>            return;
return undefined

2017-12-29 15:36 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +        console.log('err: ', err);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +          return;
return undefined

2017-12-29 15:36 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +            console.log('error', err);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +        console.log('err', err);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +          console.log('error: ', result.error);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +          console.log('something went wrong', error);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +              console.log('something went wrong', err);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +        console.log('something went wrong: ', err.message);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +        console.log('something went wrong: ', err.message);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +        console.log('something went wrong: ', err.message);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +        console.log('something went wrong: ', err.message);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +        console.log('something went wrong: ', err.message);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/header/header.component.ts
> +      console.log('err: ', err);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/header/header.component.ts
>          return;
return undefined

2017-12-29 15:36 UTC, Ugmaxie commented on src/header/header.component.ts
> +        console.log('error', err);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +      console.log('err: ', err);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
> +        console.log('error', err);
please use one temporary type of console errors: console.log or console.error

2017-12-29 15:36 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
>            console.error(res.error);
please use one temporary type of console errors: console.log or console.error

2017-12-29 16:09 UTC, Ugmaxie commented on src/signup/second-step/second-step.component.ts
>  import { extend } from 'lodash';
sure

2017-12-29 16:10 UTC, Ugmaxie approved these changes

2017-12-29 16:10 UTC, merged