refactor(header component): header component is ready for test
VS-work/live-starter pull request #44
Opened 2018-01-16 14:49 UTC by DmitriyLitvinov

- reworked markup for Header component (responsive)
  - creaded short-user-info component
  - used short-user-info component in event-info component.
  - changed User model;
  - rework Auth service

2018-01-17 08:33 UTC, dpereverzev requested changes

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.html
> +<header id="header">
id

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.html
> +            <li class="main-menu-item"><a href="#" routerLink="/artists" routerLinkActive="active" (click)="hideMenu()">Artists</a></li>
you dont need href='#'

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.html
> +                <li role="menuitem"><a class="dropdown-item" href="#" routerLink="/my-events" routerLinkActive="active" (click)="hideMenu()">My events</a></li>
href='#'

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.html
> +                   pattern="\S+@\S+\.\S+"
i'm not sure that this is the best choice to detect email

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.scss
> +  display: block;
display: block; useless with position:fixed

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.scss
> +  background: white;
hex

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.scss
> +	font-weight: 400;
tabs

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.scss
> +@media screen and (max-width: 960px) {
use mixin

2018-01-17 08:33 UTC, dpereverzev commented on src/header/header.component.scss
> +	color: #1c2e36;
use variable

2018-01-18 15:10 UTC, Ugmaxie requested changes

2018-01-18 15:10 UTC, Ugmaxie commented on src/auth/auth.service.ts
> +      if (profile) {
invert

2018-01-18 15:10 UTC, Ugmaxie commented on src/header/header.component.ts
> +      if (profile) {
invert

2018-01-19 09:32 UTC, Ugmaxie requested changes

2018-01-19 09:32 UTC, Ugmaxie commented on src/header/header.component.scss
> +  width: 100%;
width
width

2018-01-19 09:32 UTC, Ugmaxie commented on src/header/header.component.ts
> +        if (user) {
invert

2018-01-19 15:39 UTC, Ugmaxie approved these changes

2018-01-19 15:40 UTC, merged