refactoring(footer component): footer are ready for test
VS-work/live-starter pull request #45
Opened 2018-01-16 15:58 UTC by DmitriyLitvinov

- move footer component from Shared folder;
  - change styles and markup for responsive design;

2018-01-17 08:23 UTC, dpereverzev requested changes

2018-01-17 08:23 UTC, dpereverzev commented on src/footer/footer.component.html
> +<footer id="footer">
id?

2018-01-17 08:23 UTC, dpereverzev commented on src/footer/footer.component.html
> +          <a href="#" routerLink="/how-it-works" class="footer-link how-it-was">How It Works</a>
you don't need href='#' with routerLInk

2018-01-17 08:23 UTC, dpereverzev commented on src/footer/footer.component.scss
> +#footer {
try to avoid id's in styles

2018-01-17 08:23 UTC, dpereverzev commented on src/footer/footer.component.scss
> +	color: white;
IMHO: use variable color $white or use only hex #fff;

2018-01-17 08:23 UTC, dpereverzev commented on src/footer/footer.component.scss
> +@media screen and (max-width: 960px) {
i think you should create mixin with your breakpoints and use it

2018-01-18 15:12 UTC, Ugmaxie approved these changes

2018-01-18 15:12 UTC, merged