feat(event component): similar shows is ready for test
VS-work/live-starter pull request #46
Opened 2018-01-17 14:47 UTC by DmitriyLitvinov

- changed Http to HttpClient in search.sevice.ts;

2018-01-17 15:22 UTC, Ugmaxie requested changes

2018-01-17 15:22 UTC, Ugmaxie commented on src/event-launch/event.service.ts
>    public saveNewEvent(query: any): Observable<any> {
avoid any

2018-01-17 15:22 UTC, Ugmaxie commented on src/shared/search-service/search.service.ts
> +      .map((res: CustomResponse) => res)
res => res  ?

2018-01-17 15:22 UTC, Ugmaxie commented on src/shared/search-service/search.service.ts
> +      .map((res: CustomResponse) => res)
res => res ?

2018-01-17 15:46 UTC, DmitriyLitvinov commented on src/shared/search-service/search.service.ts
> +      .map((res: CustomResponse) => res)
You are right, but not now. For do It I should rework all components which use this method. It will be a big PR. I'm going to do it soon in another PR.

2018-01-17 15:46 UTC, DmitriyLitvinov commented on src/shared/search-service/search.service.ts
> +      .map((res: CustomResponse) => res)
You are right, but not now. For do It I should rework all components which use this method. It will be a big PR. I'm going to do it soon in another PR.

2018-01-18 13:51 UTC, Ugmaxie approved these changes

2018-01-18 13:52 UTC, merged