feat(my-followings): followings page is ready for test
VS-work/live-starter pull request #48
Opened 2018-01-24 11:01 UTC by DmitriyLitvinov

- created my followings page component and routes for it;
 - updated  my events page component
 - update Event model;
 - update show info component;
 - update search service;

2018-01-26 15:18 UTC, Ugmaxie requested changes

2018-01-26 15:18 UTC, Ugmaxie commented on src/shared/show-info/show-info.component.html
> +          <span class="show-name" (click)="gotoAnotherPage(false)">{{user?.username}}</span>
(click)="gotoAnotherPage(false)" ?

2018-01-26 15:18 UTC, Ugmaxie commented on src/shared/show-info/show-info.component.html
> +          <app-follow *ngIf="!isEvent" [followedUser]="user._id"></app-follow>
if user ID is a string - remove dual binding

2018-01-26 15:18 UTC, Ugmaxie commented on src/shared/show-info/show-info.component.html
> +          <app-statistics [statistics]="statistics" [id]="user._id" [isEvent]="isEvent"></app-statistics>
the same

2018-01-26 15:18 UTC, Ugmaxie commented on src/shared/show-info/show-info.component.ts
> +      return;
return undefined

2018-01-26 15:18 UTC, Ugmaxie commented on src/shared/show-info/show-info.component.ts
> +      return;
return undefined

2018-01-26 16:21 UTC, DmitriyLitvinov commented on src/shared/show-info/show-info.component.ts
> +      return;
if I do it I have TS err `TS2408: Setters cannot return a value.`

2018-01-26 16:21 UTC, DmitriyLitvinov commented on src/shared/show-info/show-info.component.ts
> +      return;
if I do it I have TS err `TS2408: Setters cannot return a value.`

2018-01-26 16:29 UTC, Ugmaxie commented on src/shared/show-info/show-info.component.ts
> +      return;
got it

2018-01-29 11:16 UTC, Ugmaxie requested changes

2018-01-29 11:16 UTC, Ugmaxie commented on src/event-launch/event-launch.model.ts
> +      likes: 0,
seems it's better to set it as a separate const.

2018-01-29 11:16 UTC, Ugmaxie commented on src/my-events/my-events.component.html
> +  <app-my-pages-header [isCreateBtn]="true"></app-my-pages-header>
avoid dual-binding
set true in html not good idea

2018-01-29 12:07 UTC, Ugmaxie approved these changes

2018-01-29 12:07 UTC, merged