feat(show page): in progress.
VS-work/live-starter pull request #57
Opened 2018-03-13 10:20 UTC by DmitriyLitvinov

- added responsive markup;
  - created timer component (only markup);
  - created shared component (only markup);
  - changed purchase component;
  - added query parameters for navigate to event page;

2018-03-13 13:14 UTC, Ugmaxie requested changes

2018-03-13 13:14 UTC, Ugmaxie commented on src/shared/share-container/share-container.component.ts
> +  constructor() { }
drop empty constructor

2018-03-13 13:14 UTC, Ugmaxie commented on src/shared/timer/timer.component.ts
> +  constructor() { }
drop empty constructor

2018-03-13 13:14 UTC, Ugmaxie commented on src/show-page/show-page.component.html
>            <app-statistics [statistics]="currentShow?.statistics" [id]="currentShow?._id"></app-statistics>
if ID is string - don't use dual binding

2018-03-13 13:14 UTC, Ugmaxie commented on src/show-page/show-page.component.html
> +        <app-timer [datePerformance]="currentShow?.datePerformance"></app-timer>
if datePerformance is a string - don't use dual binding

2018-03-13 13:14 UTC, Ugmaxie commented on src/show-page/show-page.component.ts
> +import { head } from 'lodash';
lodash-es?

2018-03-13 13:14 UTC, Ugmaxie commented on src/show-page/show-page.component.ts
>  import * as moment from 'moment';
if you use a simple moment methods which can be easily removed by native Date methods - don't use moment, it takes too much space in bundles.

2018-03-13 13:14 UTC, Ugmaxie commented on src/show-page/show-page.component.ts
> +        console.log(params);
remove console

2018-03-13 13:33 UTC, DmitriyLitvinov commented on src/show-page/show-page.component.html
>            <app-statistics [statistics]="currentShow?.statistics" [id]="currentShow?._id"></app-statistics>
This is not dual binding. It's `Input`

2018-03-13 13:33 UTC, DmitriyLitvinov commented on src/show-page/show-page.component.html
> +        <app-timer [datePerformance]="currentShow?.datePerformance"></app-timer>
This is not dual binding. It's Input

2018-03-13 17:38 UTC, Ugmaxie requested changes

2018-03-13 17:38 UTC, Ugmaxie commented on src/artist-profile/tips/tips.component.ts
> +import { forEach } from 'lodash-es';
import forEach from 'lodash-es/forEach';

2018-03-13 17:38 UTC, Ugmaxie commented on src/shared/genres-filter/genres-filter.pipe.ts
> +import { filter } from 'lodash-es';
the same as forEach

2018-03-13 17:38 UTC, Ugmaxie commented on src/shared/tips-container/tips-container.component.ts
> +  constructor() { }
remove empty constructor

2018-03-13 17:38 UTC, Ugmaxie commented on src/shared/tips-container/tips-container.component.ts
> +  ngOnInit() {
remove empty ngOnInit

2018-03-13 17:38 UTC, Ugmaxie commented on src/show-page/show-page.component.ts
> +import { head } from 'lodash-es';
the same as forEach

2018-03-14 09:57 UTC, Ugmaxie approved these changes

2018-03-14 09:57 UTC, merged