feat(fan profile): #83 is ready for test;
VS-work/live-starter pull request #85
Opened 2018-04-23 15:26 UTC by DmitriyLitvinov

2018-04-24 15:41 UTC, Ugmaxie requested changes

2018-04-24 15:41 UTC, Ugmaxie commented on src/fan-profile/fan-profile.component.ts
> +
please sort imports

2018-04-24 15:41 UTC, Ugmaxie commented on src/fan-profile/fan-profile.component.ts
> +      .subscribe(params => {
if you can use filter here - use it

2018-04-24 15:41 UTC, Ugmaxie commented on src/fan-profile/fan-profile.component.ts
> +  getBackedShows(): void | undefined {
void | undefined => void

return undefined => return void

2018-04-24 15:41 UTC, Ugmaxie commented on src/fan-profile/fan-profile.component.ts
> +  getAttendedShows(): void | undefined {
void. undefined... as above

2018-04-24 15:41 UTC, Ugmaxie commented on src/shared/show-info/show-info.component.ts
> +import { StatisticsItem } from '../statistics/statistics.interface';
please sort imports

2018-04-24 15:41 UTC, Ugmaxie commented on src/shared/statistics/statistics.component.ts
> +import { LikeRequestObj, StatisticsItem } from './statistics.interface';
please sort imports

2018-04-24 15:41 UTC, Ugmaxie commented on src/shared/statistics/statistics.component.ts
> +    if (item.title !== 'Likes') {
void, undefined...

2018-04-25 10:09 UTC, DmitriyLitvinov commented on src/fan-profile/fan-profile.component.ts
> +      .subscribe(params => {
this is router subscribe,  I think use  filter for this subscribe doesn't sense

2018-04-25 10:16 UTC, Ugmaxie requested changes

2018-04-25 10:16 UTC, Ugmaxie commented on src/fan-profile/fan-profile.component.html
> +             *ngIf="!!user.socials.facebook || !!user.socials.twitter || !!user.socials.google || !!user.socials.instagram">
What if user has facebook but doesn't have any other socials?

There's an idea to check'em separately.

2018-04-25 10:31 UTC, Ugmaxie approved these changes

2018-04-25 10:31 UTC, merged