refactoring(Users): ready for test
VS-work/live-starter pull request #87
Opened 2018-04-25 15:17 UTC by DmitriyLitvinov

2018-04-26 07:21 UTC, Ugmaxie requested changes

2018-04-26 07:21 UTC, Ugmaxie commented on src/auth0/auth.service.ts
> +    this.userService.updateUserAccount.subscribe((res: boolean): void => {
you can use filter here to avoid next "if"

2018-04-26 07:21 UTC, Ugmaxie commented on src/event-launch/event-launch.component.ts
> +import { OembedService } from '../shared/services';
Can 16 and 20 strings be imported together?

2018-04-26 07:21 UTC, Ugmaxie commented on src/shared/services/user-service/user.model.ts
> +import { RouterLinks } from '../../../enums/index';
you shouldn't use "index" in this case

2018-04-26 07:21 UTC, Ugmaxie commented on src/shared/services/user-service/user.model.ts
> +import { City, Country } from '../../models/index';
the same

2018-04-26 07:21 UTC, Ugmaxie commented on src/shared/services/user-service/user.service.ts
> +import { User, UpdateUserProfileRequestObject, UpdateUserProfileResponseObject } from './index';
you shouldn't use index file

2018-04-27 09:20 UTC, DiLiUA commented on src/auth0/auth.service.ts
> +    this.userService.updateUserAccount.subscribe((res: boolean): void => {
it makes no sense

2018-04-27 09:23 UTC, DiLiUA commented on src/event-launch/event-launch.component.ts
> +import { OembedService } from '../shared/services';
no. that's because of `user-service` has own `index.ts file`

2018-04-27 09:31 UTC, Ugmaxie approved these changes

2018-04-27 09:31 UTC, merged